/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIndexRouteImport } from './routes/Ideas/index'
import { Route as IdeasIdeaIdIndexRouteImport } from './routes/Ideas/$ideaId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/Ideas/',
  path: '/Ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdIndexRoute = IdeasIdeaIdIndexRouteImport.update({
  id: '/Ideas/$ideaId/',
  path: '/Ideas/$ideaId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Ideas': typeof IdeasIndexRoute
  '/Ideas/$ideaId': typeof IdeasIdeaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Ideas': typeof IdeasIndexRoute
  '/Ideas/$ideaId': typeof IdeasIdeaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Ideas/': typeof IdeasIndexRoute
  '/Ideas/$ideaId/': typeof IdeasIdeaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Ideas' | '/Ideas/$ideaId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Ideas' | '/Ideas/$ideaId'
  id: '__root__' | '/' | '/Ideas/' | '/Ideas/$ideaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
  IdeasIdeaIdIndexRoute: typeof IdeasIdeaIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Ideas/': {
      id: '/Ideas/'
      path: '/Ideas'
      fullPath: '/Ideas'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Ideas/$ideaId/': {
      id: '/Ideas/$ideaId/'
      path: '/Ideas/$ideaId'
      fullPath: '/Ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasIndexRoute: IdeasIndexRoute,
  IdeasIdeaIdIndexRoute: IdeasIdeaIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
